process.setMaxListeners(0);
(process as any).noDeprecation = true;

export { IInputs } from './interface';
export { Logger, ILogger } from './logger';
export { HLogger } from './decorator';
export * from './common';
export * from './libs';
export { default as unzip } from 'decompress';
export { default as chalk } from 'chalk';
export { default as colors } from 'chalk';
export { default as getMAC } from 'getmac';
export { default as fse } from 'fs-extra';
export { default as execa } from 'execa';
export { default as inquirer } from 'inquirer';
export { default as jsyaml } from 'js-yaml';
export { default as minimist } from 'minimist';
export { default as rimraf } from 'rimraf';
export { default as Crypto } from 'crypto-js';
export { default as isDocker } from 'is-docker';
export { default as semver } from 'semver';
export { default as ip } from 'ip';
export { default as ansiEscapes } from 'ansi-escapes';
export { default as ignore } from 'ignore';
export { default as minimatch } from 'minimatch';
export { default as archiver } from 'archiver';
export { default as tableLayout } from 'table-layout';
export { default as httpx } from 'httpx';
export { default as pEvent } from 'p-event';
export { default as got } from '@serverless-devs/got';
export { default as lodash } from 'lodash';
export { default as popCore } from '@alicloud/pop-core';
export { default as extend2 } from 'extend2';
